; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = atmelsam
board = nano_33_iot
framework = arduino
monitor_speed = 115200

;deps
[display]
lib_deps =
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library

[BLE]
lib_deps = 
    ;arduino-libraries/ArduinoBLE@1.3.7
    ArduinoBLE
;builds
[env:main]
build_src_filter =+<main.cpp>
lib_deps = 
    ${display.lib_deps}
    ${BLE.lib_deps}

[env:extra_button]
build_src_filter =+<extra_button.cpp>
lib_deps = 
    ${display.lib_deps}

[env:print_readings]
build_src_filter =+<print_readings.cpp>
lib_deps = 
    ${display.lib_deps}

[env:config]
build_src_filter =+<config_tf_luna.cpp>

[env:reset_start_button]
build_src_filter =+<reset_start_button.cpp>
lib_deps = 
    ${display.lib_deps}

[env:BLE_test]
build_src_filter = +<BLE_test.cpp>
lib_deps = 
    ${BLE.lib_deps}
